"""Update database schema.

Revision ID: 0148f990fbc6
Revises: b2239badf610
Create Date: 2024-07-20 11:27:39.302547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0148f990fbc6'
down_revision = 'b2239badf610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_volunteer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_recipient', sa.Boolean(), nullable=True))

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_collected', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('proof_of_delivery', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proof_of_delivery')
        batch_op.drop_column('time_collected')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_recipient')
        batch_op.drop_column('is_volunteer')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
