"""Updated database schema

Revision ID: c284cb34c608
Revises: a240d0d9304c
Create Date: 2024-07-21 22:27:21.120705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c284cb34c608'
down_revision = 'a240d0d9304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliveries', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('deliveries')

    # ### end Alembic commands ###
